# Generated by Django 4.2.7 on 2025-06-28 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cipherapp', '0002_chatmessage_linked_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=20, unique=True)),
                ('parameters', models.JSONField(default=dict)),
                ('training_sessions', models.IntegerField(default=0)),
                ('total_feedback_processed', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_trained', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('bot_response', models.TextField()),
                ('positive_feedback_count', models.IntegerField(default=0)),
                ('negative_feedback_count', models.IntegerField(default=0)),
                ('total_uses', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_keywords', models.JSONField(default=list)),
                ('response_category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-success_rate', '-total_uses'],
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Thumbs Up'), ('negative', 'Thumbs Down')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='cipherapp.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
